version: '3.8'

services:

  # metrics
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # tracing
  tempo:
    image: grafana/tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]

  # profiling
  pyroscope:
    image: pyroscope/pyroscope
    ports:
      - "4040:4040"
    command: server

  python-server:
    build:
      context: ./python-server
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

  rust-server:
    build:
      context: ./rust-server
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

volumes:
  grafana-storage:
