version: '3.8'

services:

  # dashboard
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=pyroscope-datasource,grafana-tempo-datasource
    depends_on:
      - prometheus
      - tempo
      - pyroscope

  # metrics
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # tracing
  tempo:
    image: grafana/tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]

  # profiling
  pyroscope:
    image: pyroscope/pyroscope
    ports:
      - "4040:4040"
    command: server

  # collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml

  python-server:
    build:
      context: ./python-server
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

  rust-server:
    build:
      context: ./rust-server
    ports:
      - "8001:8001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

volumes:
  grafana-storage:
